name: my_reusable_components
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5
  animated_bottom_navigation_bar: ^1.1.0
  flutter_tts: ^3.5.3
  flutter_screenutil: ^5.5.4
  lottie: ^1.4.3
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: nasalization
      fonts:
        - asset: assets/fonts/nasalization_rg.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
